apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: init-db
  name: init-db
spec:
  containers:
  - args:
    - initdb
    env:
    - name: AIRFLOW_HOME
      value: /opt/airflow/airflow
    - name: AIRFLOW__CELERY__BROKER_URL
      value: redis://redis:6379/1
    - name: AIRFLOW__CORE__BASE_LOG_FOLDER
      value: ${AIRFLOW_HOME}/logs
    - name: AIRFLOW__CORE__DAGS_FOLDER
      value: /home/airflow/.local/lib/python3.6/site-packages/data_pipelines_dags/dags
    - name: AIRFLOW__CORE__EXECUTOR
      value: CeleryExecutor
    - name: AIRFLOW__CORE__LOAD_EXAMPLES
      value: "False"
    - name: AIRFLOW__CORE__MIN_SERIALIZED_DAG_UPDATE_INTERVAL
      value: "30"
    - name: AIRFLOW__CORE__PLUGINS_FOLDER
      value: ${AIRFLOW_HOME}/plugins
    - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
      value: postgres://airflow:airflow@postgres:5432/airflow
    - name: AIRFLOW__CORE__STORE_SERIALIZED_DAGS
      value: "True"
    - name: AIRFLOW__SCHEDULER__PRINT_STATS_INTERVAL
      value: "5"
    - name: AIRFLOW__WEBSERVER__WEB_SERVER_PORT
      value: "8888"
    - name: AIRFLOW__WEBSERVER__WORKERS
      value: "1"
    - name: POSTGRES_DB
      value: airflow
    - name: POSTGRES_EXTRAS
    - name: POSTGRES_HOST
      value: postgres
    - name: POSTGRES_PASSWORD
      value: airflow
    - name: POSTGRES_PORT
      value: "5432"
    - name: POSTGRES_USER
      value: airflow
    - name: REDIS_DBNUM
      value: "1"
    - name: REDIS_HOST
      value: redis
    - name: REDIS_PASSWORD
      value: redispass
    - name: REDIS_PORT
      value: "6379"
    - name: REDIS_PROTO
      value: redis://
    image: loum/data-pipelines-infrastructure:1.10.10-0.0.0-1
    name: airflow-initdb
    resources: {}
    volumeMounts:
    - mountPath: /opt/airflow
      name: airflow-vol
  restartPolicy: Never
  volumes:
  - name: airflow-vol
    persistentVolumeClaim:
      claimName: airflow-vol
status: {}
