version: '3.7'

services:
    redis:
        image: redis:5.0.5
        container_name: airflow-redis
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}

    postgres:
        image: postgres:9.6
        container_name: airflow-postgres
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
            - PGDATA=/var/lib/postgresql/data/pgdata/db-files
        volumes:
            - postgres-vol:/var/lib/postgresql/data/pgdata/db-files
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}

    init-db:
        image: ${DATA_PIPELINES_IMAGE}
        container_name: airflow-initdb
        depends_on:
            - postgres
        env_file:
            - ./files/envfile
        user: "50000"
        volumes:
            - airflow-vol:/opt/airflow/
        restart: "no"
        command: initdb

    scheduler:
        image: ${DATA_PIPELINES_IMAGE}
        container_name: airflow-scheduler
        depends_on:
            - init-db
            - redis
        env_file:
            - ./files/envfile
        volumes:
            - airflow-vol:/opt/airflow/
        command: scheduler

    webserver:
        image: ${DATA_PIPELINES_IMAGE}
        container_name: airflow-webserver
        env_file:
            - ./files/envfile
        depends_on:
            - scheduler
        volumes:
            - airflow-vol:/opt/airflow/
        ports:
            - ${AIRFLOW__WEBSERVER__WEB_SERVER_PORT}:${AIRFLOW__WEBSERVER__WEB_SERVER_PORT}
        labels:
            kompose.service.type: LoadBalancer
        command: webserver

    worker:
        image: ${DATA_PIPELINES_IMAGE}
        container_name: airflow-worker
        env_file:
            - ./files/envfile
        depends_on:
            - scheduler
        volumes:
            - airflow-vol:/opt/airflow/
        command: worker

volumes:
    airflow-vol:
    postgres-vol:
